=== olgamomirov/XWS-Projekat32/kosrinickimodul.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:complexType name="TPretraga" abstract="true">
        <xs:sequence>
            <xs:element name="Mesto" type="TMesto"/>
            <xs:element name="Vremenski_interval" type="TVremenskiInterval"/>
            <xs:element name="Broj_osoba">
                <xs:simpleType>
                    <xs:restriction base="xs:int">
                        <xs:minInclusive value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TMesto">
        <xs:sequence>
            <xs:element name="Drzava">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="3"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Grad">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="3"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TVremenskiInterval">
        <xs:sequence>
            <xs:element name="Datum_dolaska" type="xs:date"/>
            <xs:element name="Datum_povratka" type="xs:date"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TOsnovnaPretraga">
        <xs:complexContent>
            <xs:extension base="TPretraga"/>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TNaprednaPretraga">
        <xs:complexContent>
            <xs:extension base="TPretraga">
                <xs:sequence>
                    <xs:element name="Tip_smestaja">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element minOccurs="0" name="Hotel"/>
                                <xs:element minOccurs="0" name="Bed_and_breakfast"/>
                                <xs:element minOccurs="0" name="Apartman"/>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="Kategorija_smestaja">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element minOccurs="0" name="Nekategorisan"/>
                                <xs:element minOccurs="0" name="Zvezdica_1"/>
                                <xs:element minOccurs="0" name="Zvezdica_2"/>
                                <xs:element minOccurs="0" name="Zvezdica_3"/>
                                <xs:element minOccurs="0" name="Zvezdica_4"/>
                                <xs:element minOccurs="0" name="Zvezdica_5"/>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="Udaljenost_od_lokacije">
                        <xs:simpleType>
                            <xs:restriction base="xs:int">
                                <xs:minInclusive value="0"/>
                                <xs:maxInclusive value="2147483647"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                    <xs:element name="Dodatne_usluge" maxOccurs="1" minOccurs="1">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="Parking" type="TDodatneUsluge"/>
                                <xs:element name="WiFi" type="TDodatneUsluge"/>
                                <xs:element name="Dorucak" type="TDodatneUsluge"/>
                                <xs:element name="Polu_pansion" type="TDodatneUsluge"/>
                                <xs:element name="Pansion" type="TDodatneUsluge"/>
                                <xs:element name="All_inclusive" type="TDodatneUsluge"/>
                                <xs:element name="Kucni_ljubimci" type="TDodatneUsluge"/>
                                <xs:element name="TV" type="TDodatneUsluge"/>
                                <xs:element name="Mini_kuhinja-kuhinja" type="TDodatneUsluge"/>
                                <xs:element name="Privatno_kupatilo" type="TDodatneUsluge"/>
                                <xs:element name="Besplatno_otkazivanje">
                                    <xs:complexType>
                                        <xs:complexContent>
                                            <xs:extension base="TDodatneUsluge">
                                                <xs:sequence>
                                                  <xs:element minOccurs="0" name="Datum"
                                                  type="xs:date"/>
                                                </xs:sequence>
                                            </xs:extension>
                                        </xs:complexContent>
                                    </xs:complexType>
                                </xs:element>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TDodatneUsluge">
        <xs:attribute form="unqualified" name="podrzano" type="xs:boolean" use="required"/>
    </xs:complexType>
    <xs:element name="Korisnik">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Pretraga" type="TPretraga"/>
                <xs:element name="Registracija">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Rezervacija">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Poruke"/>
                                        <xs:element name="Otkazivanje"/>
                                        <xs:element name="Ocena_i_komentar"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== olgamomirov/XWS-Projekat32/proba2.xml
<?xml version="1.0" encoding="UTF-8"?>
<Korisnik xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/C:/Users/OlgaM/Desktop/kosrinickimodul.xsd">
    <Pretraga xsi:type="TNaprednaPretraga">
        <Mesto>
            <Drzava>Spanija</Drzava>
            <Grad>Madrid</Grad>
        </Mesto>
        <Vremenski_interval>
            <Datum_dolaska>2018-11-09</Datum_dolaska>
            <Datum_povratka>2018-11-15</Datum_povratka>
        </Vremenski_interval>
        <Broj_osoba>2</Broj_osoba>
        <Tip_smestaja></Tip_smestaja>
        <Kategorija_smestaja></Kategorija_smestaja>
        <Udaljenost_od_lokacije>12</Udaljenost_od_lokacije> 
        <Dodatne_usluge/>
        
    </Pretraga>
</Korisnik>

=== olgamomirov/XWS-Projekat32/proba1.xml
<?xml version="1.0" encoding="UTF-8"?>
<Korisnik xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/C:/Users/OlgaM/Desktop/kosrinickimodul.xsd">
    <Pretraga xsi:type="TNaprednaPretraga">
        <Mesto>
            <Drzava></Drzava>
            <Grad></Grad>
        </Mesto>
        <Vremenski_interval>
            <Datum_dolaska>2010-10-11</Datum_dolaska>
            <Datum_povratka>2010-11-10</Datum_povratka>
        </Vremenski_interval>
        <Broj_osoba>12</Broj_osoba>
        <Tip_smestaja></Tip_smestaja>
    </Pretraga>
</Korisnik>

=== olgamomirov/XWS-Projekat32/napredna_pretraga.xml
<?xml version="1.0" encoding="UTF-8"?>
<Korisnik xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/C:/Users/OlgaM/Desktop/kosrinickimodul.xsd">
    <Pretraga xsi:type="TNaprednaPretraga">
        <Mesto>
            <Drzava>Spanija</Drzava>
            <Grad>Madrid</Grad>
        </Mesto>
        <Vremenski_interval>
            <Datum_dolaska>2018-11-09</Datum_dolaska>
            <Datum_povratka>2018-11-15</Datum_povratka>
        </Vremenski_interval>
        <Broj_osoba>2</Broj_osoba>
        <Tip_smestaja>
            <Hotel></Hotel>
        </Tip_smestaja>
        <Kategorija_smestaja>
            <Zvezdica_3></Zvezdica_3>
        </Kategorija_smestaja>
        <Udaljenost_od_lokacije>15</Udaljenost_od_lokacije>
        <Dodatne_usluge>
            <Parking podrzano="true"/>
            <WiFi podrzano="true"/>
            <Dorucak podrzano="true"/>
            <Polu_pansion podrzano="false"/>
            <Pansion podrzano="false"/>
            <All_inclusive podrzano="false"/>
            <Kucni_ljubimci podrzano="true"/>
            <TV podrzano="true"/>
            <Mini_kuhinja-kuhinja podrzano="true"/>
            <Privatno_kupatilo podrzano="true"/>
            <Besplatno_otkazivanje podrzano="false"/>
        </Dodatne_usluge>
    </Pretraga>
</Korisnik>
